CREATE DATABASE assessment;
USE assessment;

CREATE TABLE `group` (
    id INT PRIMARY KEY AUTO_INCREMENT,
    groupName VARCHAR(255) NOT NULL,
    parentGroupId INT,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (parentGroupId) REFERENCES `group`(id) ON DELETE SET NULL
);

CREATE TABLE person (
    id INT PRIMARY KEY AUTO_INCREMENT,
    firstName VARCHAR(255) NOT NULL,
    lastName VARCHAR(255) NOT NULL,
    jobTitle VARCHAR(255) NOT NULL,
    groupId INT,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (groupId) REFERENCES `group`(id) ON DELETE SET NULL
);
